services:
  backend:
    image: 874043936756.dkr.ecr.eu-central-1.amazonaws.com/keto-backend:latest
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    image: 874043936756.dkr.ecr.eu-central-1.amazonaws.com/keto-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
